/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_marakana_FibLib */

#ifndef _Included_com_marakana_FibLib
#define _Included_com_marakana_FibLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_marakana_FibLib
 * Method:    fibN
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_marakana_FibLib_fibN
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
